### ISSUE TITLE
Default configuration includes paste remaps to system clipboard

### ISSUE THREAD

**Issue by JayLCypher** [mei28/luminate.nvim#15]
From commit fe3951486f73dbd699b972e511fcada0f77dd89a.

The default configuration includes the keybind '"+p', which pastes from system clipboard. This is breaking behavior from vim defaults.
Since there is no cooperating rebind with yank, setting the put keybind also breaks vim default yank/put behavior.
Yank still places to register 0 and increments registers, while put always puts from + register.

Suggest that having system clipboard either be part of custom config only and fallback to vim defaults or whatever remaps the user has specified for p (such as say ' ""p ') since if the user is using a different put register, logic should follow that they also update their yank register.

**Comment by mei28** [comment]
Thank you for your report.

I implemented the current behavior because I didn't fully understand the registers in Vim/Neovim. 
If I change the configuration from `map = { p = '"+p', P = '"+P' }` to `map = { p = 'p', P = 'P' }`, will this correct the issue while maintaining the yank/put behavior?

If there are any other problems, please let me know.

Thank you.

**Comment by JayLCypher** [comment]
Nice turnaround.

I just changed it in the same vein as what you did with undos, just map it to "p" and "P".
```lua
	map = { p = "p", P = "P" },
```
